### ISSUE TITLE
set y-axis via parameters for uniform plotting

### ISSUE THREAD

**Issue by laurenzse** [engelfa/TuK1-CPU#4]

**Comment by boeckhoff** [comment]
specify range for y-axis

**Comment by Chaoste** [comment]
Suggestion: 
Instead of 
```
  data = generate_data(
        [...],
        'gb_per_sec')
```
we might write
```
  data = generate_data(
        [...],
        {'yParam': 'gb_per_sec', 'bounds': (X, Y)}')
```

This requires adaption of the storage code to also store this config in the pickles. Thereby, it is not that easy to adapt the limits afterwards in the plotting code.

Alternatively, this might be defined by constants in utils/viz.py oder a parameter in generate_plots().
