### ISSUE TITLE
enable parallel execution on multiple cores/processors

### ISSUE THREAD

**Issue by boeckhoff** [engelfa/TuK1-CPU#9]

**Comment by engelfa** [comment]
numactl:
bind 10 scans on one core

**Comment by Chaoste** [comment]
I used "taskset" to define the CPU affinity of each spawned subprocess. There are some config constants at the beginning of file "exe_utils.py".

"CONCURRENCY" (=40) - number of spawned subprocess at one time
"PROCESS_PER_CPU" (=10) - number of subprocess on one CPU

**Comment by Chaoste** [comment]
Currently the tqdm progress bar only updates on dispatching the processes.

If we want to see when each process is done, there might a workaround: For each spawned subprocess spawn a sepearate thread in the main process listening to the regarding subprocess (with `.join()`). Since it shares the memory with the main thread it may update the progress bar manually (should be named something like `bar.update()`).
